### ISSUE TITLE
Triaxial Test Type

### ISSUE THREAD

**Issue by sdeaton75** [DIGGSml/schema-dev#47]
We need codelists for triaxial tests - ones for total stress and another list for effective stress.

The total stress values I propose are:
UNC  - unconfined compression test
UU - UU triaxial test
UUM - mulitpoint UU triaxial test

For effective stress triaxial tests I propose:
CD - Consolidated Drained with pwp measurement (single stage)
CDM - Consolidated drained (multi-stage)
CU - Consolidated undrained with pwp measurement (single stage)
CUM - Consolidated undrained with pwp measurement (multi-stage)

Then we can get into some more unusual ones 
CADC - Consolidated Anisotropically drained compression with pwp measurement
CADE - Consolidated Anisotropically drained extension with pwp measurement
CAUC - Anisotropically consolidated undrained compression with pwp measurement
CAUE - Anisotropically consolidated undrained extension with pwp measurement
CIDC - Isotropically consolidated drained compression with pwp measurement
CIDE - Isotropically consolidated drained extension with pwp measurement
UUP - Unconsolidated undrained with pwp measurement

**Comment by acadden-SE** [comment]
Looks like a good list.  Spell out Unconsolidated Undrained in the definitions for UU and UUM.  We should also spell out somewhere what pwp is -  pore water pressure

**Comment by dponti** [comment]
These codes and their definitions are now included in a DIGGS dictionary (https://diggsml.org/def/codes/DIGGS/0.1/triaxType.xml)
