### ISSUE TITLE
CBR Issues

### ISSUE THREAD

**Issue by sdeaton75** [DIGGSml/schema-dev#54]
There are a few things I have found when implementing CBR Testing using DIGGS.

First, the calculatedStress element has the wrong units definition. It is currently setup to only accept force units not stress. This is incorrect.

![image](https://github.com/user-attachments/assets/45ac91ce-2293-4567-a3cc-d4b5acf021d6)

Also the CBRIncrement should allow either calculatedStress or MeasuredLoad.  Ultimately you need the stress to process the test, but the raw data would be the measured load and deflection, so there should be an option to only transmit load and deflection.

**Comment by sdeaton75** [comment]
All 3 properties should be available.  We just need to change calculatedStress uom a stress uom.

**Comment by dponti** [comment]
Latest push of the schema to this repository now has:
1) calculatedStress and measuredLoad as optional elements. Both or either can be used. measuredPenetration remains as a mandatory element
2) calculatedStress type changed to eml:PressureMeasureExt instead of force, which was an error.
